/*
 * JAVA期末專題
 * 4102029018 陳欣儀
 * 引用請註明來源
 */

package addressbook;
import java.io.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Little Mouse
 */
public class BookViewer extends JFrame {

    /**
     * Creates new form BookViewer
     */
    BookReader abr = new BookReader();
    ArrayList list;
    
    public BookViewer() {
        initComponents();
    }
    public void display(AddressBook ab){
        NameField.setText(ab.getName());
        MobileNoField.setText(ab.getNumber());
        BirthdayField.setText(ab.getBirthday());
        MailAdrField.setText(ab.getMailAddress());
        if(ab instanceof Relatives){
            Relatives r = (Relatives) ab;
            CategoryBox.setSelectedIndex(0);
            Attribute1Label.setText("關係");
            Attribute1Field.setText(r.getRelationship());
            Attribute2Label.setText("住家電話");
            Attribute2Field.setText(r.getPhoneNumber());
        }
        if(ab instanceof Colleague){
            CategoryBox.setSelectedIndex(1);
            Colleague c = (Colleague) ab;
            Attribute1Label.setText("部門");
            Attribute1Field.setText(c.getDepartment());
            Attribute2Label.setText("部門電話");
            Attribute2Field.setText(c.getDepartmentNumber());
        }
        if(ab instanceof Friend){
            CategoryBox.setSelectedIndex(2);
            Friend f = (Friend) ab;
            Attribute1Label.setText("暱稱");
            Attribute1Field.setText(f.getNickname());
            Attribute2Label.setText("住家地址");
            Attribute2Field.setText(f.getHouseAddress());
         }    
    }
    public void displayList(ArrayList list2, int type){
        AddressBook ab;
        DefaultListModel dlm = new DefaultListModel();
        String[] number = new String[list2.size()];
        for (Object list1 : list2) {
            ab = (AddressBook) list1;
           number[list2.indexOf(list1)] = ab.getNumber();
            switch(type){
                case 1:
                    if(ab instanceof Relatives)
                        dlm.addElement(ab.getNumber());
                    break;
                case 2:
                    if(ab instanceof Colleague)
                        dlm.addElement(ab.getNumber());
                    break;
                case 3:
                    if(ab instanceof Friend)
                        dlm.addElement(ab.getNumber());
                    break;
                default:
                    dlm.addElement(ab.getNumber());
            }
        }
        jList1.setModel(dlm);
    }
    public void setEditable (boolean b){
        if(b == true){
            NameField.setEditable(true);
            CategoryBox.setEnabled(true);
            MobileNoField.setEditable(true);
            BirthdayField.setEditable(true);
            Attribute1Field.setEditable(true);
            Attribute2Field.setEditable(true);
            MailAdrField.setEditable(true);
            ConfirmButton.setEnabled(true);
        }
        else{
            NameField.setEditable(false);
            CategoryBox.setEnabled(false);
            MobileNoField.setEditable(false);
            BirthdayField.setEditable(false);
            Attribute1Field.setEditable(false);
            Attribute2Field.setEditable(false);
            MailAdrField.setEditable(false);
            ConfirmButton.setEnabled(false);
        }
    }
    public void clear(){
        NameField.setText("");
        CategoryBox.setSelectedIndex(0);
        MobileNoField.setText("");
        BirthdayField.setText("");
        Attribute1Field.setText("");
        Attribute2Field.setText("");
        MailAdrField.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jPanel1d = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2d = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3d = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        AddButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        DeleteButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        EditButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        SearchButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        AllButton = new javax.swing.JRadioButton();
        RelativesButton = new javax.swing.JRadioButton();
        ColleagueButton = new javax.swing.JRadioButton();
        FriendButton = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        CategoryLabel = new javax.swing.JLabel();
        CategoryBox = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        MobileNoLabel = new javax.swing.JLabel();
        MobileNoField = new javax.swing.JFormattedTextField();
        jPanel12 = new javax.swing.JPanel();
        BirthdayLabel = new javax.swing.JLabel();
        BirthdayField = new javax.swing.JFormattedTextField();
        jPanel13 = new javax.swing.JPanel();
        Attribute1Label = new javax.swing.JLabel();
        Attribute1Field = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        Attribute2Label = new javax.swing.JLabel();
        Attribute2Field = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        MailAdrLabel = new javax.swing.JLabel();
        MailAdrField = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        ConfirmButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenFile = new javax.swing.JMenuItem();
        SaveFile = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        jDialog1.setTitle("關於");

        jLabel1.setFont(new java.awt.Font("新細明體", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("通訊錄管理");
        jDialog1.getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1d.setLayout(new java.awt.GridLayout(4, 1));

        jLabel2.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("聯絡方式：gc.little.piece@gmail.com");
        jPanel1d.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("中興資管  JAVA物件導向程式設計  期末專題");
        jPanel1d.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4102029018  陳欣儀");
        jPanel1d.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("指導老師：呂瑞麟");
        jPanel1d.add(jLabel5);

        jDialog1.getContentPane().add(jPanel1d, java.awt.BorderLayout.CENTER);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Build time:2014.6");

        javax.swing.GroupLayout jPanel2dLayout = new javax.swing.GroupLayout(jPanel2d);
        jPanel2d.setLayout(jPanel2dLayout);
        jPanel2dLayout.setHorizontalGroup(
            jPanel2dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2dLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2dLayout.setVerticalGroup(
            jPanel2dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2dLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDialog1.getContentPane().add(jPanel2d, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel3dLayout = new javax.swing.GroupLayout(jPanel3d);
        jPanel3d.setLayout(jPanel3dLayout);
        jPanel3dLayout.setHorizontalGroup(
            jPanel3dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3dLayout.setVerticalGroup(
            jPanel3dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        jDialog1.getContentPane().add(jPanel3d, java.awt.BorderLayout.LINE_START);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("通訊錄管理");

        jPanel1.setLayout(new java.awt.GridLayout(1, 4));

        AddButton.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        AddButton.setText("增加");
        AddButton.setToolTipText("增加聯絡人");
        AddButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(AddButton)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel3);

        DeleteButton.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        DeleteButton.setText("刪除");
        DeleteButton.setToolTipText("刪除聯絡人");
        DeleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(DeleteButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel4);

        EditButton.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        EditButton.setText("修改");
        EditButton.setToolTipText("修改聯絡人");
        EditButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(EditButton)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel5);

        SearchButton.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        SearchButton.setText("查詢");
        SearchButton.setToolTipText("依姓名查詢聯絡人");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(SearchButton)
                .addGap(45, 45, 45))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "電話清單", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("微軟正黑體", 0, 12), java.awt.Color.darkGray)); // NOI18N

        jList1.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setToolTipText("");
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        buttonGroup1.add(AllButton);
        AllButton.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        AllButton.setSelected(true);
        AllButton.setText("全部");
        AllButton.setToolTipText("顯示全部電話");
        AllButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AllButtonItemStateChanged(evt);
            }
        });
        AllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(RelativesButton);
        RelativesButton.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        RelativesButton.setText("親戚");
        RelativesButton.setToolTipText("只顯示親戚的電話");
        RelativesButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RelativesButtonItemStateChanged(evt);
            }
        });
        RelativesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelativesButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(ColleagueButton);
        ColleagueButton.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        ColleagueButton.setText("同事");
        ColleagueButton.setToolTipText("只顯示同事的電話");
        ColleagueButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ColleagueButtonItemStateChanged(evt);
            }
        });

        buttonGroup1.add(FriendButton);
        FriendButton.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        FriendButton.setText("友人");
        FriendButton.setToolTipText("只顯示友人的電話");
        FriendButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FriendButtonItemStateChanged(evt);
            }
        });
        FriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(AllButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RelativesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ColleagueButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FriendButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AllButton)
                    .addComponent(RelativesButton)
                    .addComponent(ColleagueButton)
                    .addComponent(FriendButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "詳細資訊", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("微軟正黑體", 0, 12), java.awt.Color.darkGray)); // NOI18N
        jPanel8.setLayout(new java.awt.GridLayout(4, 2));

        NameLabel.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        NameLabel.setText("姓名");

        NameField.setEditable(false);
        NameField.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        NameField.setToolTipText("請勿輸入空格");
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(NameLabel)
                .addGap(18, 18, 18)
                .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel8.add(jPanel9);

        CategoryLabel.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        CategoryLabel.setText("類別");
        CategoryLabel.setToolTipText("");

        CategoryBox.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        CategoryBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "親戚", "同事", "友人" }));
        CategoryBox.setEnabled(false);
        CategoryBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CategoryBoxItemStateChanged(evt);
            }
        });
        CategoryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CategoryLabel)
                .addGap(18, 18, 18)
                .addComponent(CategoryBox, 0, 71, Short.MAX_VALUE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoryLabel))
                .addGap(32, 32, 32))
        );

        jPanel8.add(jPanel10);

        jPanel11.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N

        MobileNoLabel.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        MobileNoLabel.setText("手機號碼");

        MobileNoField.setEditable(false);
        MobileNoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0000000000"))));
        MobileNoField.setToolTipText("請勿輸入空格");
        MobileNoField.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(MobileNoLabel)
                .addGap(18, 18, 18)
                .addComponent(MobileNoField, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MobileNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MobileNoLabel))
                .addGap(32, 32, 32))
        );

        jPanel8.add(jPanel11);

        BirthdayLabel.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        BirthdayLabel.setText("生日");
        BirthdayLabel.setToolTipText("");

        BirthdayField.setEditable(false);
        BirthdayField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        BirthdayField.setToolTipText("西元年/月/日");
        BirthdayField.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        BirthdayField.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BirthdayLabel)
                .addGap(18, 18, 18)
                .addComponent(BirthdayField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BirthdayLabel)
                    .addComponent(BirthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel8.add(jPanel12);

        Attribute1Label.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        Attribute1Label.setText("關係");

        Attribute1Field.setEditable(false);
        Attribute1Field.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        Attribute1Field.setToolTipText("請勿輸入空格");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Attribute1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(Attribute1Field, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Attribute1Label)
                    .addComponent(Attribute1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel8.add(jPanel13);

        Attribute2Label.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        Attribute2Label.setText("住家電話");

        Attribute2Field.setEditable(false);
        Attribute2Field.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        Attribute2Field.setToolTipText("請勿輸入空格");
        Attribute2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Attribute2FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Attribute2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Attribute2Field, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Attribute2Label)
                    .addComponent(Attribute2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel14);

        MailAdrLabel.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        MailAdrLabel.setText("電子信箱");

        MailAdrField.setEditable(false);
        MailAdrField.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        MailAdrField.setToolTipText("請勿輸入空格");
        MailAdrField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailAdrFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(MailAdrLabel)
                .addGap(18, 18, 18)
                .addComponent(MailAdrField)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MailAdrLabel)
                    .addComponent(MailAdrField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel8.add(jPanel15);

        ConfirmButton.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        ConfirmButton.setText("確認");
        ConfirmButton.setEnabled(false);
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(ConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel8.add(jPanel16);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        FileMenu.setText("檔案");
        FileMenu.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        FileMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FileMenuMouseClicked(evt);
            }
        });

        OpenFile.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        OpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addressbook/open-file-icon.png"))); // NOI18N
        OpenFile.setText("開啟檔案");
        OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileActionPerformed(evt);
            }
        });
        FileMenu.add(OpenFile);

        SaveFile.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        SaveFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addressbook/Save-icon.png"))); // NOI18N
        SaveFile.setText("儲存檔案");
        SaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileActionPerformed(evt);
            }
        });
        FileMenu.add(SaveFile);

        jMenuBar1.add(FileMenu);

        AboutMenu.setText("關於");
        AboutMenu.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N

        About.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addressbook/information-icon.png"))); // NOI18N
        About.setText("關於");
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
        });
        AboutMenu.add(About);

        jMenuBar1.add(AboutMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileActionPerformed
        displayList(abr.open(), 0);
    }//GEN-LAST:event_OpenFileActionPerformed

    private void FileMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FileMenuMouseClicked
       //TODO add your handling code here:
    }//GEN-LAST:event_FileMenuMouseClicked

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        jDialog1.setVisible(true);
    }//GEN-LAST:event_AboutMouseClicked

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        clear();
        setEditable(true);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void CategoryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryBoxActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        int index = CategoryBox.getSelectedIndex();
        switch(index){
            case 0:
                Relatives r = new Relatives(NameField.getText(),MobileNoField.getText());
                r.setBirthday(BirthdayField.getText());
                r.setMailAddress(MailAdrField.getText());                
                r.setRelationship(Attribute1Field.getText());
                r.setPhoneNumber(Attribute2Field.getText());
                 abr.update(r);
                break;
            case 1:
                Colleague c = new Colleague(NameField.getText(),MobileNoField.getText());
                c.setBirthday(BirthdayField.getText());
                c.setMailAddress(MailAdrField.getText());
                c.setDepartment(Attribute1Field.getText());
                c.setDepartNumber(Attribute2Field.getText());
                abr.update(c);
                break;
            default:
                Friend f = new Friend(NameField.getText(),MobileNoField.getText());
                f.setBirthday(BirthdayField.getText());
                f.setMailAddress(MailAdrField.getText());
                f.setNickname(Attribute1Field.getText());
                f.setHouseAddress(Attribute2Field.getText());
                abr.update(f);
                break;
        }
        setEditable(false);
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void RelativesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelativesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelativesButtonActionPerformed

    private void FriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriendButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FriendButtonActionPerformed

    private void MailAdrFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailAdrFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailAdrFieldActionPerformed

    private void SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileActionPerformed
       int ans =  JOptionPane.showConfirmDialog(null, "是否要儲存檔案？", "儲存檔案", JOptionPane.YES_NO_OPTION);
        if (ans == JOptionPane.YES_OPTION){
            try{
                String name = JOptionPane.showInputDialog(null,"請輸入檔名：","儲存檔案",JOptionPane.INFORMATION_MESSAGE);
                abr.save(name);
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, "檔案開啟錯誤", "錯誤",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_SaveFileActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        setEditable(false);
        String n = "";
        try{
            n = JOptionPane.showInputDialog(null, "請輸入姓名：", "查詢", JOptionPane.QUESTION_MESSAGE);
            AddressBook ab = (AddressBook) abr.search(n);
            display(ab);
        }catch(NumberFormatException | NullPointerException e){
            JOptionPane.showMessageDialog(null, "找不到" + n + "！", "Oops！", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void Attribute2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Attribute2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Attribute2FieldActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        setEditable(true);
    }//GEN-LAST:event_EditButtonActionPerformed

    private void CategoryBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CategoryBoxItemStateChanged
        if(CategoryBox.getSelectedIndex() == 0){
            Attribute1Label.setText("關係");
            Attribute2Label.setText("住家電話");
        }
        if(CategoryBox.getSelectedIndex() == 1){
            Attribute1Label.setText("部門");
            Attribute2Label.setText("部門電話");
        }
        if(CategoryBox.getSelectedIndex() == 2){
            Attribute1Label.setText("暱稱");
            Attribute2Label.setText("住家地址");
        }
    }//GEN-LAST:event_CategoryBoxItemStateChanged

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        String name = abr.delete(NameField.getText());
        setEditable(false);
        JOptionPane.showMessageDialog(null, "已刪除" + name + "！", "刪除成功！", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        int index = jList1.getSelectedIndex();
        display((AddressBook) abr.updateList().get(index));
        
    }//GEN-LAST:event_jList1ValueChanged

    private void AllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllButtonActionPerformed
        //TODO ass your handling code here:
    }//GEN-LAST:event_AllButtonActionPerformed

    private void AllButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AllButtonItemStateChanged
        if(((JRadioButton) evt.getSource()).isSelected()){
            displayList(abr.updateList(), 0);
        }        
    }//GEN-LAST:event_AllButtonItemStateChanged

    private void RelativesButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RelativesButtonItemStateChanged
        if(((JRadioButton) evt.getSource()).isSelected()){
            displayList(abr.updateList(), 1);
        }
    }//GEN-LAST:event_RelativesButtonItemStateChanged

    private void ColleagueButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ColleagueButtonItemStateChanged
        if(((JRadioButton) evt.getSource()).isSelected()){
            displayList(abr.updateList(), 2);
        }
    }//GEN-LAST:event_ColleagueButtonItemStateChanged

    private void FriendButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FriendButtonItemStateChanged
        if(((JRadioButton) evt.getSource()).isSelected()){
            displayList(abr.updateList(), 3);
        }
    }//GEN-LAST:event_FriendButtonItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenu AboutMenu;
    private javax.swing.JButton AddButton;
    private javax.swing.JRadioButton AllButton;
    private javax.swing.JTextField Attribute1Field;
    private javax.swing.JLabel Attribute1Label;
    private javax.swing.JTextField Attribute2Field;
    private javax.swing.JLabel Attribute2Label;
    private javax.swing.JFormattedTextField BirthdayField;
    private javax.swing.JLabel BirthdayLabel;
    private javax.swing.JComboBox CategoryBox;
    private javax.swing.JLabel CategoryLabel;
    private javax.swing.JRadioButton ColleagueButton;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JRadioButton FriendButton;
    private javax.swing.JTextField MailAdrField;
    private javax.swing.JLabel MailAdrLabel;
    private javax.swing.JFormattedTextField MobileNoField;
    private javax.swing.JLabel MobileNoLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JMenuItem OpenFile;
    private javax.swing.JRadioButton RelativesButton;
    private javax.swing.JMenuItem SaveFile;
    private javax.swing.JButton SearchButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel1d;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2d;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel3d;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
